name: "S3 Upload"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Delete files from the output S3 bucket - after parsing
        # if: ${{ startsWith(github.ref_name, 'staging') }}
        run: |
          echo Deleting all files on s3://uk.co.johnholcroft.visualchemicalsafety.${{ github.ref_name }}-json
          aws s3 rm s3://uk.co.johnholcroft.visualchemicalsafety.${{ github.ref_name }}-json --recursive

      - name: Copy files to the source S3 bucket - will be parsed and written to the output S3 bucket
        # if: ${{ startsWith(github.ref_name, 'staging') }}
        run: |
          echo Syncing all files to s3://uk.co.johnholcroft.visualchemicalsafety.${{ github.ref_name }}/public
          aws s3 sync . s3://uk.co.johnholcroft.visualchemicalsafety.${{ github.ref_name }}/public --exclude ".git*/*" --delete
